grumphp:
  fixer:
    enabled: false
    fix_by_default: false
  tasks:
    composer: null
    git_blacklist:
      keywords:
        - "dump("
        - "var_dump("
        - "print_r("
        - "die("
        - "exit("
        - "exit;"
    git_commit_message:
      enforce_capitalized_subject: false
      type_scope_conventions:
        types:
          - build
          - ci
          - chore
          - docs
          - feat
          - fix
          - perf
          - refactor
          - revert
          - style
          - test
        scopes: []
    composer_script:
      scripts:
        - test:yaml
        - test:twig
    phpcsfixer:
      config: .php-cs-fixer.dist.php
    phpstan:
      configuration: ~
